version: '3.8'
name: aws-ui-minio-example
services:
  minio:
    image: minio/minio:latest
    command: server /minio-data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    expose:
      - '9000'
    volumes:
      - './.minio:/minio-data'
      - '/var/run/docker.sock:/var/run/docker.sock'
  aws-ui:
    container_name: aws-ui
    image: dabolus/aws-ui:nightly
    ports:
      - '8080:8080'
    environment:
      AWS_UI_S3_SERVICE_ENDPOINT: http://minio:9000
      AWS_UI_S3_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_UI_S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
